






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace demo.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace demo.Models.sitecore.templates.Page_Types
{


 	/// <summary>
	/// IHomeStartBootstrap Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeStartBootstrap</para>	
	/// <para>ID: 4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeStartBootstrapConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHomeStartBootstrap : IGlassBase 
	{
			
	}


	public static partial class IHomeStartBootstrapConstants{

			public const string TemplateIdString = "4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomeStartBootstrap";

			

	}

	
	/// <summary>
	/// HomeStartBootstrap
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeStartBootstrap</para>	
	/// <para>ID: 4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeStartBootstrapConstants.TemplateIdString)] //, Cachable = true
	public partial class HomeStartBootstrap  : GlassBase, IHomeStartBootstrap 
	{
	   
			
	}

}
namespace demo.Models.sitecore.templates.Content_Type
{


 	/// <summary>
	/// ICTA Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/CTA</para>	
	/// <para>ID: 66a4da94-51db-4cad-8dd2-576943c2d1a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICTAConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICTA : IGlassBase , global::demo.Models.sitecore.templates.Base.Content.I_HasContent, global::demo.Models.sitecore.templates.Base.Content.I_HasDestination
	{
			
	}


	public static partial class ICTAConstants{

			public const string TemplateIdString = "66a4da94-51db-4cad-8dd2-576943c2d1a4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CTA";

		
			
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
			

	}

	
	/// <summary>
	/// CTA
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/CTA</para>	
	/// <para>ID: 66a4da94-51db-4cad-8dd2-576943c2d1a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICTAConstants.TemplateIdString)] //, Cachable = true
	public partial class CTA  : GlassBase, ICTA 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
			
	}

}
namespace demo.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasContent</para>	
	/// <para>ID: 728070e0-57d0-4722-882e-98ce37a40650</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasContent : IGlassBase 
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasContentConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasContentConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class I_HasContentConstants{

			public const string TemplateIdString = "728070e0-57d0-4722-882e-98ce37a40650";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasContent";

		
			
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// _HasContent
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasContent</para>	
	/// <para>ID: 728070e0-57d0-4722-882e-98ce37a40650</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasContentConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasContent  : GlassBase, I_HasContent 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasContentConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasContentConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace demo.Models.sitecore.templates.Content_Type
{


 	/// <summary>
	/// IJumbotron Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Jumbotron</para>	
	/// <para>ID: 8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IJumbotronConstants.TemplateIdString )] //, Cachable = true
	public partial interface IJumbotron : IGlassBase , global::demo.Models.sitecore.templates.Base.Content.I_HasContent, global::demo.Models.sitecore.templates.Base.Content.I_HasDestination, global::demo.Models.sitecore.templates.Base.Content.I_HasImage
	{
			
	}


	public static partial class IJumbotronConstants{

			public const string TemplateIdString = "8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Jumbotron";

		
			
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
		
			
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// Jumbotron
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Jumbotron</para>	
	/// <para>ID: 8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IJumbotronConstants.TemplateIdString)] //, Cachable = true
	public partial class Jumbotron  : GlassBase, IJumbotron 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}

}
namespace demo.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasImage</para>	
	/// <para>ID: 9e43a519-f46a-4f5c-905f-6d4b7c6a84a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasImage : IGlassBase 
	{
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
	}


	public static partial class I_HasImageConstants{

			public const string TemplateIdString = "9e43a519-f46a-4f5c-905f-6d4b7c6a84a3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasImage";

		
			
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// _HasImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasImage</para>	
	/// <para>ID: 9e43a519-f46a-4f5c-905f-6d4b7c6a84a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasImageConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasImage  : GlassBase, I_HasImage 
	{
	   
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasImageConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}

}
namespace demo.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasDestination Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasDestination</para>	
	/// <para>ID: b9242340-a680-4cbf-a4cf-2c1144a84bb2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasDestination : IGlassBase 
	{
			
					/// <summary>
					/// The Destination field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasDestinationConstants.DestinationFieldName)]
					Link Destination  {get; set;}
			
			
	}


	public static partial class I_HasDestinationConstants{

			public const string TemplateIdString = "b9242340-a680-4cbf-a4cf-2c1144a84bb2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasDestination";

		
			
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
			

	}

	
	/// <summary>
	/// _HasDestination
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasDestination</para>	
	/// <para>ID: b9242340-a680-4cbf-a4cf-2c1144a84bb2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasDestination  : GlassBase, I_HasDestination 
	{
	   
		
				/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasDestinationConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
			
	}

}
namespace demo.Models.sitecore.templates.Page_Types
{


 	/// <summary>
	/// IHomeDemo Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeDemo</para>	
	/// <para>ID: bf614f84-4b74-4739-be95-304426c48d19</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeDemoConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHomeDemo : IGlassBase 
	{
			
	}


	public static partial class IHomeDemoConstants{

			public const string TemplateIdString = "bf614f84-4b74-4739-be95-304426c48d19";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomeDemo";

			

	}

	
	/// <summary>
	/// HomeDemo
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeDemo</para>	
	/// <para>ID: bf614f84-4b74-4739-be95-304426c48d19</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeDemoConstants.TemplateIdString)] //, Cachable = true
	public partial class HomeDemo  : GlassBase, IHomeDemo 
	{
	   
			
	}

}
namespace demo.Models.sitecore.templates.Content_Type
{


 	/// <summary>
	/// ICar Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Car</para>	
	/// <para>ID: ca707291-87ed-463a-acd0-ed650a1c16a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICar : IGlassBase , global::demo.Models.sitecore.templates.Base.Content.I_HasContent, global::demo.Models.sitecore.templates.Base.Content.I_HasImage
	{
			
					/// <summary>
					/// The Make field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d4ab707b-7196-4168-9f33-9a5ec1107867</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.MakeFieldName)]
					string Make  {get; set;}
			
			
					/// <summary>
					/// The Model field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ec89dd18-3959-4f43-907c-e88efc374de1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.ModelFieldName)]
					string Model  {get; set;}
			
			
					/// <summary>
					/// The Year field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 1c5470bd-bd27-448b-bfa9-675abf41a33c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.YearFieldName)]
					float Year  {get; set;}
			
			
	}


	public static partial class ICarConstants{

			public const string TemplateIdString = "ca707291-87ed-463a-acd0-ed650a1c16a4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Car";

		
			
			public static readonly ID MakeFieldId = new ID("d4ab707b-7196-4168-9f33-9a5ec1107867");
			public const string MakeFieldName = "Make";
			
		
			
			public static readonly ID ModelFieldId = new ID("ec89dd18-3959-4f43-907c-e88efc374de1");
			public const string ModelFieldName = "Model";
			
		
			
			public static readonly ID YearFieldId = new ID("1c5470bd-bd27-448b-bfa9-675abf41a33c");
			public const string YearFieldName = "Year";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// Car
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Car</para>	
	/// <para>ID: ca707291-87ed-463a-acd0-ed650a1c16a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarConstants.TemplateIdString)] //, Cachable = true
	public partial class Car  : GlassBase, ICar 
	{
	   
		
				/// <summary>
				/// The Make field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d4ab707b-7196-4168-9f33-9a5ec1107867</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.MakeFieldName)]
				public virtual string Make  {get; set;}
					
		
				/// <summary>
				/// The Model field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ec89dd18-3959-4f43-907c-e88efc374de1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.ModelFieldName)]
				public virtual string Model  {get; set;}
					
		
				/// <summary>
				/// The Year field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 1c5470bd-bd27-448b-bfa9-675abf41a33c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.YearFieldName)]
				public virtual float Year  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}

}
