





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace startbootstrap.demo.com.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumnImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ColumnImage</para>	
	/// <para>ID: 0babcfd7-029d-4af7-b461-8c09a9f41be5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumnImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IColumnImage : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasDestination
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 6bbc0800-9b44-4706-812b-5689a349df2a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IColumnImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Category field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a30df8b8-c5a4-47e4-a700-ede0b7d2a0e6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IColumnImageConstants.CategoryFieldName)]
					string Category  {get; set;}
			
								/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 71592d4d-c95a-4660-afc3-8a2ced4bd10d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IColumnImageConstants.NameFieldName)]
					string Name  {get; set;}
			
				}


	public static partial class IColumnImageConstants{

			public const string TemplateIdString = "0babcfd7-029d-4af7-b461-8c09a9f41be5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ColumnImage";

					
			public static readonly ID ImageFieldId = new ID("6bbc0800-9b44-4706-812b-5689a349df2a");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID CategoryFieldId = new ID("a30df8b8-c5a4-47e4-a700-ede0b7d2a0e6");
			public const string CategoryFieldName = "Category";
			
					
			public static readonly ID NameFieldId = new ID("71592d4d-c95a-4660-afc3-8a2ced4bd10d");
			public const string NameFieldName = "Name";
			
					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
			

	}

	
	/// <summary>
	/// ColumnImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ColumnImage</para>	
	/// <para>ID: 0babcfd7-029d-4af7-b461-8c09a9f41be5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumnImageConstants.TemplateIdString)] //, Cachable = true
	public partial class ColumnImage  : GlassBase, IColumnImage 
	{
	   
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 6bbc0800-9b44-4706-812b-5689a349df2a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumnImageConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Category field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a30df8b8-c5a4-47e4-a700-ede0b7d2a0e6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumnImageConstants.CategoryFieldName)]
				public virtual string Category  {get; set;}
					
						/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 71592d4d-c95a-4660-afc3-8a2ced4bd10d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumnImageConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumnImageConstants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content
{


 	/// <summary>
	/// I_HasIntroduction Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasIntroduction</para>	
	/// <para>ID: 0e9e9277-2bf4-404d-a81d-ff3e0570aad2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasIntroductionConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasIntroduction : IGlassBase 
	{
								/// <summary>
					/// The Introduction field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasIntroductionConstants.IntroductionFieldName)]
					string Introduction  {get; set;}
			
				}


	public static partial class I_HasIntroductionConstants{

			public const string TemplateIdString = "0e9e9277-2bf4-404d-a81d-ff3e0570aad2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasIntroduction";

					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
			

	}

	
	/// <summary>
	/// _HasIntroduction
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasIntroduction</para>	
	/// <para>ID: 0e9e9277-2bf4-404d-a81d-ff3e0570aad2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasIntroductionConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasIntroduction  : GlassBase, I_HasIntroduction 
	{
	   
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasIntroductionConstants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.Parameters
{


 	/// <summary>
	/// ICSSClassParam Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Parameters/CSSClassParam</para>	
	/// <para>ID: 27fc12f0-9fb6-4300-991b-7c6e260f92b1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICSSClassParamConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICSSClassParam : IGlassBase 
	{
								/// <summary>
					/// The Class_1 field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e0246ae0-b6f8-4fe9-a989-89325933c373</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICSSClassParamConstants.Class_1FieldName)]
					string Class_1  {get; set;}
			
								/// <summary>
					/// The Class_2 field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: bac3e1e0-7ff9-4328-883c-2153383ff4e1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICSSClassParamConstants.Class_2FieldName)]
					string Class_2  {get; set;}
			
				}


	public static partial class ICSSClassParamConstants{

			public const string TemplateIdString = "27fc12f0-9fb6-4300-991b-7c6e260f92b1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CSSClassParam";

					
			public static readonly ID Class_1FieldId = new ID("e0246ae0-b6f8-4fe9-a989-89325933c373");
			public const string Class_1FieldName = "Class_1";
			
					
			public static readonly ID Class_2FieldId = new ID("bac3e1e0-7ff9-4328-883c-2153383ff4e1");
			public const string Class_2FieldName = "Class_2";
			
			

	}

	
	/// <summary>
	/// CSSClassParam
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Parameters/CSSClassParam</para>	
	/// <para>ID: 27fc12f0-9fb6-4300-991b-7c6e260f92b1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICSSClassParamConstants.TemplateIdString)] //, Cachable = true
	public partial class CSSClassParam  : GlassBase, ICSSClassParam 
	{
	   
						/// <summary>
				/// The Class_1 field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e0246ae0-b6f8-4fe9-a989-89325933c373</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICSSClassParamConstants.Class_1FieldName)]
				public virtual string Class_1  {get; set;}
					
						/// <summary>
				/// The Class_2 field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: bac3e1e0-7ff9-4328-883c-2153383ff4e1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICSSClassParamConstants.Class_2FieldName)]
				public virtual string Class_2  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IContentDarkAside Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ContentDarkAside</para>	
	/// <para>ID: 425e7e88-282c-4995-8610-b20afe1003a6</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContentDarkAsideConstants.TemplateIdString )] //, Cachable = true
	public partial interface IContentDarkAside : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasDestination
	{
				}


	public static partial class IContentDarkAsideConstants{

			public const string TemplateIdString = "425e7e88-282c-4995-8610-b20afe1003a6";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ContentDarkAside";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
			

	}

	
	/// <summary>
	/// ContentDarkAside
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ContentDarkAside</para>	
	/// <para>ID: 425e7e88-282c-4995-8610-b20afe1003a6</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContentDarkAsideConstants.TemplateIdString)] //, Cachable = true
	public partial class ContentDarkAside  : GlassBase, IContentDarkAside 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContentDarkAsideConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContentDarkAsideConstants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Page_Types
{


 	/// <summary>
	/// IHomeStartBootstrap Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeStartBootstrap</para>	
	/// <para>ID: 4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeStartBootstrapConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHomeStartBootstrap : IGlassBase 
	{
				}


	public static partial class IHomeStartBootstrapConstants{

			public const string TemplateIdString = "4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomeStartBootstrap";

			

	}

	
	/// <summary>
	/// HomeStartBootstrap
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeStartBootstrap</para>	
	/// <para>ID: 4f6a29fa-3ff5-4ba0-b3aa-768d88aba77e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeStartBootstrapConstants.TemplateIdString)] //, Cachable = true
	public partial class HomeStartBootstrap  : GlassBase, IHomeStartBootstrap 
	{
	   
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IContentHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ContentHeader</para>	
	/// <para>ID: 56df96f4-7d3b-486b-9f97-d84993f775aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContentHeaderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IContentHeader : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasIntroduction, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasDestination
	{
				}


	public static partial class IContentHeaderConstants{

			public const string TemplateIdString = "56df96f4-7d3b-486b-9f97-d84993f775aa";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ContentHeader";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
			

	}

	
	/// <summary>
	/// ContentHeader
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/ContentHeader</para>	
	/// <para>ID: 56df96f4-7d3b-486b-9f97-d84993f775aa</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContentHeaderConstants.TemplateIdString)] //, Cachable = true
	public partial class ContentHeader  : GlassBase, IContentHeader 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContentHeaderConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContentHeaderConstants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IContentHeaderConstants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo01
{


 	/// <summary>
	/// ICTA Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/CTA</para>	
	/// <para>ID: 66a4da94-51db-4cad-8dd2-576943c2d1a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICTAConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICTA : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasContent, global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasDestination
	{
				}


	public static partial class ICTAConstants{

			public const string TemplateIdString = "66a4da94-51db-4cad-8dd2-576943c2d1a4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CTA";

					
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
			

	}

	
	/// <summary>
	/// CTA
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/CTA</para>	
	/// <para>ID: 66a4da94-51db-4cad-8dd2-576943c2d1a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICTAConstants.TemplateIdString)] //, Cachable = true
	public partial class CTA  : GlassBase, ICTA 
	{
	   
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICTAConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasContent</para>	
	/// <para>ID: 728070e0-57d0-4722-882e-98ce37a40650</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasContent : IGlassBase 
	{
								/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasContentConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasContentConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class I_HasContentConstants{

			public const string TemplateIdString = "728070e0-57d0-4722-882e-98ce37a40650";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasContent";

					
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// _HasContent
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasContent</para>	
	/// <para>ID: 728070e0-57d0-4722-882e-98ce37a40650</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasContentConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasContent  : GlassBase, I_HasContent 
	{
	   
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasContentConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasContentConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumn_Lg12 Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg12</para>	
	/// <para>ID: 74922fd8-253e-4b57-bb04-06afe2b93abf</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg12Constants.TemplateIdString )] //, Cachable = true
	public partial interface IColumn_Lg12 : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle
	{
				}


	public static partial class IColumn_Lg12Constants{

			public const string TemplateIdString = "74922fd8-253e-4b57-bb04-06afe2b93abf";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Column_lg12";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Column_Lg12
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg12</para>	
	/// <para>ID: 74922fd8-253e-4b57-bb04-06afe2b93abf</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg12Constants.TemplateIdString)] //, Cachable = true
	public partial class Column_Lg12  : GlassBase, IColumn_Lg12 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg12Constants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content
{


 	/// <summary>
	/// I_HasDestination Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasDestination</para>	
	/// <para>ID: 7b12c3cc-34aa-4dc0-8ab2-4f5d05b038f8</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasDestination : IGlassBase 
	{
								/// <summary>
					/// The URL field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasDestinationConstants.URLFieldName)]
					Link URL  {get; set;}
			
				}


	public static partial class I_HasDestinationConstants{

			public const string TemplateIdString = "7b12c3cc-34aa-4dc0-8ab2-4f5d05b038f8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasDestination";

					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
			

	}

	
	/// <summary>
	/// _HasDestination
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasDestination</para>	
	/// <para>ID: 7b12c3cc-34aa-4dc0-8ab2-4f5d05b038f8</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasDestination  : GlassBase, I_HasDestination 
	{
	   
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasDestinationConstants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumn_Lg8_Contact Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg8_Contact</para>	
	/// <para>ID: 84998581-2681-4c02-8722-d64cc64e47f3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg8_ContactConstants.TemplateIdString )] //, Cachable = true
	public partial interface IColumn_Lg8_Contact : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasIntroduction
	{
				}


	public static partial class IColumn_Lg8_ContactConstants{

			public const string TemplateIdString = "84998581-2681-4c02-8722-d64cc64e47f3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Column_lg8_Contact";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
			

	}

	
	/// <summary>
	/// Column_Lg8_Contact
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg8_Contact</para>	
	/// <para>ID: 84998581-2681-4c02-8722-d64cc64e47f3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg8_ContactConstants.TemplateIdString)] //, Cachable = true
	public partial class Column_Lg8_Contact  : GlassBase, IColumn_Lg8_Contact 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg8_ContactConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg8_ContactConstants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo01
{


 	/// <summary>
	/// IJumbotron Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/Jumbotron</para>	
	/// <para>ID: 8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IJumbotronConstants.TemplateIdString )] //, Cachable = true
	public partial interface IJumbotron : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasContent, global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasDestination, global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasImage
	{
				}


	public static partial class IJumbotronConstants{

			public const string TemplateIdString = "8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Jumbotron";

					
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
					
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// Jumbotron
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/Jumbotron</para>	
	/// <para>ID: 8df1e2eb-65e9-4cbf-b9f2-0e909cd2ea5b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IJumbotronConstants.TemplateIdString)] //, Cachable = true
	public partial class Jumbotron  : GlassBase, IJumbotron 
	{
	   
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IJumbotronConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumn_Lg4 Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg4</para>	
	/// <para>ID: 8e436040-6eaf-4b34-ae31-03c0bc601da1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg4Constants.TemplateIdString )] //, Cachable = true
	public partial interface IColumn_Lg4 : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasDestination, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasIntroduction
	{
				}


	public static partial class IColumn_Lg4Constants{

			public const string TemplateIdString = "8e436040-6eaf-4b34-ae31-03c0bc601da1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Column_lg4";

					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
			

	}

	
	/// <summary>
	/// Column_Lg4
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg4</para>	
	/// <para>ID: 8e436040-6eaf-4b34-ae31-03c0bc601da1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg4Constants.TemplateIdString)] //, Cachable = true
	public partial class Column_Lg4  : GlassBase, IColumn_Lg4 
	{
	   
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg4Constants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg4Constants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasImage</para>	
	/// <para>ID: 9e43a519-f46a-4f5c-905f-6d4b7c6a84a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasImage : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
				}


	public static partial class I_HasImageConstants{

			public const string TemplateIdString = "9e43a519-f46a-4f5c-905f-6d4b7c6a84a3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasImage";

					
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// _HasImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasImage</para>	
	/// <para>ID: 9e43a519-f46a-4f5c-905f-6d4b7c6a84a3</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasImageConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasImage  : GlassBase, I_HasImage 
	{
	   
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasImageConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.Parameters
{


 	/// <summary>
	/// IBackGroundParam Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Parameters/BackGroundParam</para>	
	/// <para>ID: af36832b-bea1-49d9-aaa8-d06e75d73bb9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBackGroundParamConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBackGroundParam : IGlassBase 
	{
								/// <summary>
					/// The BackgroundImg field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 0ca75508-e11d-4860-b9c2-d40b5671e338</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBackGroundParamConstants.BackgroundImgFieldName)]
					Image BackgroundImg  {get; set;}
			
				}


	public static partial class IBackGroundParamConstants{

			public const string TemplateIdString = "af36832b-bea1-49d9-aaa8-d06e75d73bb9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "BackGroundParam";

					
			public static readonly ID BackgroundImgFieldId = new ID("0ca75508-e11d-4860-b9c2-d40b5671e338");
			public const string BackgroundImgFieldName = "BackgroundImg";
			
			

	}

	
	/// <summary>
	/// BackGroundParam
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Parameters/BackGroundParam</para>	
	/// <para>ID: af36832b-bea1-49d9-aaa8-d06e75d73bb9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBackGroundParamConstants.TemplateIdString)] //, Cachable = true
	public partial class BackGroundParam  : GlassBase, IBackGroundParam 
	{
	   
						/// <summary>
				/// The BackgroundImg field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 0ca75508-e11d-4860-b9c2-d40b5671e338</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBackGroundParamConstants.BackgroundImgFieldName)]
				public virtual Image BackgroundImg  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.Content
{


 	/// <summary>
	/// I_HasDestination Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasDestination</para>	
	/// <para>ID: b9242340-a680-4cbf-a4cf-2c1144a84bb2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasDestination : IGlassBase 
	{
								/// <summary>
					/// The Destination field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasDestinationConstants.DestinationFieldName)]
					Link Destination  {get; set;}
			
				}


	public static partial class I_HasDestinationConstants{

			public const string TemplateIdString = "b9242340-a680-4cbf-a4cf-2c1144a84bb2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasDestination";

					
			public static readonly ID DestinationFieldId = new ID("14e2d05f-a3bd-4613-bbbb-f46443b98b20");
			public const string DestinationFieldName = "Destination";
			
			

	}

	
	/// <summary>
	/// _HasDestination
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/Content/_HasDestination</para>	
	/// <para>ID: b9242340-a680-4cbf-a4cf-2c1144a84bb2</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasDestinationConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasDestination  : GlassBase, I_HasDestination 
	{
	   
						/// <summary>
				/// The Destination field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 14e2d05f-a3bd-4613-bbbb-f46443b98b20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasDestinationConstants.DestinationFieldName)]
				public virtual Link Destination  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Page_Types
{


 	/// <summary>
	/// IHomeDemo Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeDemo</para>	
	/// <para>ID: bf614f84-4b74-4739-be95-304426c48d19</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeDemoConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHomeDemo : IGlassBase 
	{
				}


	public static partial class IHomeDemoConstants{

			public const string TemplateIdString = "bf614f84-4b74-4739-be95-304426c48d19";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomeDemo";

			

	}

	
	/// <summary>
	/// HomeDemo
	/// <para></para>
	/// <para>Path: /sitecore/templates/Page Types/HomeDemo</para>	
	/// <para>ID: bf614f84-4b74-4739-be95-304426c48d19</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeDemoConstants.TemplateIdString)] //, Cachable = true
	public partial class HomeDemo  : GlassBase, IHomeDemo 
	{
	   
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo01
{


 	/// <summary>
	/// ICar Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/Car</para>	
	/// <para>ID: ca707291-87ed-463a-acd0-ed650a1c16a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICar : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasContent, global::startbootstrap.demo.com.Models.sitecore.templates.Base.Content.I_HasImage
	{
								/// <summary>
					/// The Make field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d4ab707b-7196-4168-9f33-9a5ec1107867</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.MakeFieldName)]
					string Make  {get; set;}
			
								/// <summary>
					/// The Model field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ec89dd18-3959-4f43-907c-e88efc374de1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.ModelFieldName)]
					string Model  {get; set;}
			
								/// <summary>
					/// The Year field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 1c5470bd-bd27-448b-bfa9-675abf41a33c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarConstants.YearFieldName)]
					float Year  {get; set;}
			
				}


	public static partial class ICarConstants{

			public const string TemplateIdString = "ca707291-87ed-463a-acd0-ed650a1c16a4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Car";

					
			public static readonly ID MakeFieldId = new ID("d4ab707b-7196-4168-9f33-9a5ec1107867");
			public const string MakeFieldName = "Make";
			
					
			public static readonly ID ModelFieldId = new ID("ec89dd18-3959-4f43-907c-e88efc374de1");
			public const string ModelFieldName = "Model";
			
					
			public static readonly ID YearFieldId = new ID("1c5470bd-bd27-448b-bfa9-675abf41a33c");
			public const string YearFieldName = "Year";
			
					
			public static readonly ID DescriptionFieldId = new ID("82f27516-e5c8-44d6-ac84-eb1b92015426");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID TitleFieldId = new ID("2514cda6-5867-4151-a5fd-b96b33cc8225");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID ImageFieldId = new ID("58f43e4d-a896-4bac-9c96-9ca78bb8bbc7");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// Car
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo01/Car</para>	
	/// <para>ID: ca707291-87ed-463a-acd0-ed650a1c16a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarConstants.TemplateIdString)] //, Cachable = true
	public partial class Car  : GlassBase, ICar 
	{
	   
						/// <summary>
				/// The Make field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d4ab707b-7196-4168-9f33-9a5ec1107867</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.MakeFieldName)]
				public virtual string Make  {get; set;}
					
						/// <summary>
				/// The Model field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ec89dd18-3959-4f43-907c-e88efc374de1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.ModelFieldName)]
				public virtual string Model  {get; set;}
					
						/// <summary>
				/// The Year field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 1c5470bd-bd27-448b-bfa9-675abf41a33c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.YearFieldName)]
				public virtual float Year  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 82f27516-e5c8-44d6-ac84-eb1b92015426</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2514cda6-5867-4151-a5fd-b96b33cc8225</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 58f43e4d-a896-4bac-9c96-9ca78bb8bbc7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumn_Lg3 Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg3</para>	
	/// <para>ID: e1995d75-6b58-4f44-a5e6-da746943170f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg3Constants.TemplateIdString )] //, Cachable = true
	public partial interface IColumn_Lg3 : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasIntroduction
	{
				}


	public static partial class IColumn_Lg3Constants{

			public const string TemplateIdString = "e1995d75-6b58-4f44-a5e6-da746943170f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Column_lg3";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
			

	}

	
	/// <summary>
	/// Column_Lg3
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg3</para>	
	/// <para>ID: e1995d75-6b58-4f44-a5e6-da746943170f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg3Constants.TemplateIdString)] //, Cachable = true
	public partial class Column_Lg3  : GlassBase, IColumn_Lg3 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg3Constants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg3Constants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Content_Type.Demo02
{


 	/// <summary>
	/// IColumn_Lg8_About Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg8_About</para>	
	/// <para>ID: e591c260-643a-4323-91cd-2dbbae0747be</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg8_AboutConstants.TemplateIdString )] //, Cachable = true
	public partial interface IColumn_Lg8_About : IGlassBase , global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasTitle, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasIntroduction, global::startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content.I_HasDestination
	{
				}


	public static partial class IColumn_Lg8_AboutConstants{

			public const string TemplateIdString = "e591c260-643a-4323-91cd-2dbbae0747be";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Column_lg8_About";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID IntroductionFieldId = new ID("dc01d647-e14f-42c0-9ff1-f05c2397ec7a");
			public const string IntroductionFieldName = "Introduction";
			
					
			public static readonly ID URLFieldId = new ID("8385df47-ec14-4679-b07b-21dbf27cc7ee");
			public const string URLFieldName = "URL";
			
			

	}

	
	/// <summary>
	/// Column_Lg8_About
	/// <para></para>
	/// <para>Path: /sitecore/templates/Content Type/Demo02/Column_lg8_About</para>	
	/// <para>ID: e591c260-643a-4323-91cd-2dbbae0747be</para>	
	/// </summary>
	[SitecoreType(TemplateId=IColumn_Lg8_AboutConstants.TemplateIdString)] //, Cachable = true
	public partial class Column_Lg8_About  : GlassBase, IColumn_Lg8_About 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg8_AboutConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Introduction field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: dc01d647-e14f-42c0-9ff1-f05c2397ec7a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg8_AboutConstants.IntroductionFieldName)]
				public virtual string Introduction  {get; set;}
					
						/// <summary>
				/// The URL field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 8385df47-ec14-4679-b07b-21dbf27cc7ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IColumn_Lg8_AboutConstants.URLFieldName)]
				public virtual Link URL  {get; set;}
					
			
	}
}
namespace startbootstrap.demo.com.Models.sitecore.templates.Base.SB_Content
{


 	/// <summary>
	/// I_HasTitle Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasTitle</para>	
	/// <para>ID: f14cecbc-127f-456f-8a7c-94f2afd50dcb</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasTitleConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HasTitle : IGlassBase 
	{
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HasTitleConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class I_HasTitleConstants{

			public const string TemplateIdString = "f14cecbc-127f-456f-8a7c-94f2afd50dcb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_HasTitle";

					
			public static readonly ID TitleFieldId = new ID("987e3bb3-f000-420a-b3f5-4d8234eb9480");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// _HasTitle
	/// <para></para>
	/// <para>Path: /sitecore/templates/Base/SB_Content/_HasTitle</para>	
	/// <para>ID: f14cecbc-127f-456f-8a7c-94f2afd50dcb</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HasTitleConstants.TemplateIdString)] //, Cachable = true
	public partial class _HasTitle  : GlassBase, I_HasTitle 
	{
	   
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 987e3bb3-f000-420a-b3f5-4d8234eb9480</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_HasTitleConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
